import type { ArtistProfile } from "@/components/artist-profile/types";

export const ARTIST_PROFILES: ArtistProfile[] = [
  {
    id: "ngoc-tram",
    name: "Ngọc Trâm",
    district: "Liên Chiểu",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup1.jpg",
    avatar: "/images/avatar.png",
    bio: "Với hơn 5 năm kinh nghiệm trong ngành trang điểm cô dâu và sự kiện, tôi luôn cam kết mang đến vẻ đẹp tự nhiên, phù hợp với từng khách hàng. Tôi đã phục vụ hàng trăm cô dâu và sẽ luôn cố gắng hết mình để ngày trọng đại của bạn thật hoàn hảo.",
    bookingArea: "Liên Chiểu, Hải Châu, Thanh Khê – Đà Nẵng",
    workPrinciples: [
      "Luôn tư vấn kỹ lưỡng trước khi thực hiện",
      "Sử dụng sản phẩm chính hãng, an toàn cho da",
      "Đúng giờ và chuyên nghiệp",
      "Hỗ trợ touch-up trong suốt sự kiện nếu cần",
    ],
    stats: { profiles: 120, reviews: 98, services: 5, agreements: 200 },
    portfolio: [
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Sự kiện" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Chụp ảnh" },
    ],
    services: [
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1500000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 600000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "photo",   concept: "Trang điểm chụp ảnh", price: 700000,  duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Tư vấn concept ảnh"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 300000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên", "Phù hợp đi làm, đi học"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "travel",  concept: "Trang điểm du lịch",  price: 450000,  duration: "1 giờ",  includes: ["Makeup bền màu", "Chịu nắng và nước tốt"], description: ["Makeup bền màu, chịu nắng và nước tốt", "Phong cách tươi sáng, tự nhiên phù hợp ảnh du lịch", "Sử dụng sản phẩm chống nắng tích hợp trong makeup", "Di chuyển đến địa điểm theo yêu cầu", "Tư vấn màu sắc phù hợp bối cảnh du lịch", "Hoàn thành trong vòng 1 giờ"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Minh Châu",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "12/05/2025",
        rating: 5,
        comment: "Chị Trâm trang điểm rất đẹp, phong cách tự nhiên đúng ý tôi. Chị rất tận tâm và chuyên nghiệp.",
        reply: "Cảm ơn bạn rất nhiều! Rất vui được phục vụ bạn trong ngày đặc biệt đó.",
      },
      {
        id: "r2",
        reviewerName: "Hà Phương",
        reviewerLocation: "Liên Chiểu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "03/04/2025",
        rating: 5,
        comment: "Trang điểm cô dâu cho đám cưới của mình, chị làm rất tỉ mỉ và đúng giờ. Makeup giữ được cả ngày dài.",
      },
      {
        id: "r3",
        reviewerName: "Nguyễn Thảo",
        reviewerLocation: "Thanh Khê, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "18/03/2025",
        rating: 5,
        comment: "Rất hài lòng với dịch vụ. Chị tư vấn rất kỹ và makeup đúng với mong muốn của mình.",
        reply: "Cảm ơn bạn đã tin tưởng! Chúc bạn luôn xinh đẹp nhé.",
      },
    ],
  },
  {
    id: "nt-my-hanh",
    name: "N.T.Mỹ Hạnh",
    district: "Hải Châu",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup2.jpg",
    avatar: "/images/avatar.png",
    bio: "Chuyên trang điểm cô dâu và sự kiện cao cấp tại Hải Châu. Tôi yêu thích phong cách trang điểm nhẹ nhàng, tinh tế, giúp mỗi khách hàng toả sáng đúng cách trong từng dịp đặc biệt.",
    bookingArea: "Hải Châu, Cẩm Lệ, Ngũ Hành Sơn – Đà Nẵng",
    workPrinciples: [
      "Tư vấn phong cách phù hợp với khuôn mặt",
      "Cam kết makeup bền màu cả ngày",
      "Sử dụng sản phẩm không gây kích ứng da",
      "Phục vụ tận nơi theo yêu cầu",
    ],
    stats: { profiles: 95, reviews: 82, services: 4, agreements: 170 },
    portfolio: [
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Du lịch" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Sự kiện" },
    ],
    services: [
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1400000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 550000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "travel",  concept: "Trang điểm du lịch",  price: 420000,  duration: "1 giờ",  includes: ["Makeup bền màu", "Chịu nắng và nước tốt"], description: ["Makeup bền màu, chịu nắng và nước tốt", "Phong cách tươi sáng, tự nhiên phù hợp ảnh du lịch", "Sử dụng sản phẩm chống nắng tích hợp trong makeup", "Di chuyển đến địa điểm theo yêu cầu", "Tư vấn màu sắc phù hợp bối cảnh du lịch", "Hoàn thành trong vòng 1 giờ"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 280000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên", "Phù hợp đi làm, đi học"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Linh Chi",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "20/05/2025",
        rating: 5,
        comment: "Chị Hạnh làm makeup cô dâu cho mình, rất đẹp và tự nhiên. Chị rất nhiệt tình từ lúc tư vấn đến khi hoàn thành.",
        reply: "Cảm ơn Linh Chi nhiều lắm! Chúc hai bạn hạnh phúc mãi nhé.",
      },
      {
        id: "r2",
        reviewerName: "Bảo Ngọc",
        reviewerLocation: "Cẩm Lệ, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "08/04/2025",
        rating: 5,
        comment: "Makeup cho buổi chụp ảnh kỷ yếu, chị làm rất nhanh mà đẹp. Cả nhóm ai cũng khen.",
      },
    ],
  },
  {
    id: "thanh-thanh",
    name: "Thanh Thanh",
    district: "Ngũ Hành Sơn",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup5.jpg",
    avatar: "/images/avatar.png",
    bio: "Với niềm đam mê làm đẹp từ nhỏ, tôi đã trau dồi kỹ năng trang điểm qua nhiều năm thực hành. Tôi chú trọng vào việc làm nổi bật vẻ đẹp riêng của từng người thay vì áp đặt một phong cách cố định.",
    bookingArea: "Ngũ Hành Sơn, Hải Châu, Sơn Trà – Đà Nẵng",
    workPrinciples: [
      "Lắng nghe và thấu hiểu mong muốn khách hàng",
      "Không dùng sản phẩm hết hạn hoặc không rõ nguồn gốc",
      "Giữ gìn vệ sinh dụng cụ trang điểm",
      "Luôn có mặt đúng giờ hẹn",
    ],
    stats: { profiles: 80, reviews: 74, services: 4, agreements: 145 },
    portfolio: [
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Hằng ngày" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Chụp ảnh" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Cô dâu" },
    ],
    services: [
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 250000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên", "Phù hợp đi làm, đi học"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "photo",   concept: "Trang điểm chụp ảnh", price: 650000,  duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Tư vấn concept ảnh"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1300000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 500000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Thu Nga",
        reviewerLocation: "Ngũ Hành Sơn, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "15/05/2025",
        rating: 5,
        comment: "Makeup đẹp, tự nhiên, đúng ý mình. Chị Thanh Thanh rất thân thiện và chuyên nghiệp.",
        reply: "Cảm ơn bạn đã tin tưởng chọn mình nhé! Hẹn gặp lại.",
      },
      {
        id: "r2",
        reviewerName: "Kim Anh",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "02/04/2025",
        rating: 5,
        comment: "Đặt lịch cho buổi tiệc sinh nhật, chị tư vấn phong cách rất hợp. Mình rất thích kết quả.",
      },
    ],
  },
  {
    id: "thu-hien",
    name: "Thu Hiền",
    district: "Sơn Trà",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup1.jpg",
    avatar: "/images/avatar.png",
    bio: "Tôi là chuyên gia trang điểm với hơn 4 năm kinh nghiệm, đặc biệt thành thạo trong trang điểm sự kiện và cô dâu phong cách Hàn Quốc. Khách hàng luôn là ưu tiên hàng đầu của tôi.",
    bookingArea: "Sơn Trà, Ngũ Hành Sơn – Đà Nẵng",
    workPrinciples: [
      "Phong cách Hàn Quốc tự nhiên làm chủ đạo",
      "Tư vấn sản phẩm skincare trước khi makeup",
      "Giá cả minh bạch, không phát sinh",
      "Hỗ trợ chụp hình check makeup miễn phí",
    ],
    stats: { profiles: 75, reviews: 68, services: 5, agreements: 130 },
    portfolio: [
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Phong cách Hàn" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Sự kiện" },
    ],
    services: [
      { id: "korean",  concept: "Trang điểm phong cách Hàn", price: 600000, duration: "1–2 giờ", includes: ["Makeup Hàn Quốc tự nhiên", "Skincare prep trước makeup"], description: ["Phong cách trang điểm Hàn Quốc tự nhiên, trong sáng", "Skincare prep trước khi makeup để da căng bóng", "Sử dụng sản phẩm từ thương hiệu Hàn Quốc uy tín", "Tư vấn màu son, phấn phù hợp với tone da", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1350000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 550000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "photo",   concept: "Trang điểm chụp ảnh", price: 650000,  duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Tư vấn concept ảnh"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 270000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên", "Phong cách Hàn Quốc"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Thanh Hoa",
        reviewerLocation: "Sơn Trà, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "10/05/2025",
        rating: 5,
        comment: "Chị Hiền làm makeup Hàn Quốc rất đẹp, đúng trend. Mình rất hài lòng và sẽ quay lại.",
        reply: "Cảm ơn bạn nhiều! Mình rất vui khi bạn thích nhé.",
      },
      {
        id: "r2",
        reviewerName: "Phương Vy",
        reviewerLocation: "Ngũ Hành Sơn, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "22/03/2025",
        rating: 5,
        comment: "Makeup cho buổi lễ tốt nghiệp, chị làm nhanh và rất cẩn thận. Cả lớp ai cũng khen mình hôm đó.",
      },
    ],
  },
  {
    id: "ny-my-cuong",
    name: "N.Y.Mỹ Cường",
    district: "Cẩm Lệ",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup2.jpg",
    avatar: "/images/avatar.png",
    bio: "Chuyên gia trang điểm tại Cẩm Lệ với đam mê mang lại vẻ đẹp rạng rỡ cho mọi phụ nữ. Tôi có kinh nghiệm phục vụ nhiều loại sự kiện từ cưới hỏi, tiệc sinh nhật đến chụp ảnh thương mại.",
    bookingArea: "Cẩm Lệ, Liên Chiểu, Hải Châu – Đà Nẵng",
    workPrinciples: [
      "Đặt sự an toàn của da khách hàng lên hàng đầu",
      "Luôn patch test sản phẩm trước khi sử dụng",
      "Phong cách linh hoạt theo yêu cầu",
      "Đảm bảo giờ giấc và cam kết hợp đồng",
    ],
    stats: { profiles: 88, reviews: 76, services: 6, agreements: 155 },
    portfolio: [
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Sự kiện" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Thương mại" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Cô dâu" },
    ],
    services: [
      { id: "event",     concept: "Trang điểm sự kiện",  price: 580000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "commercial",concept: "Trang điểm thương mại", price: 900000, duration: "2–3 giờ", includes: ["Makeup quảng cáo / sản phẩm", "Phối hợp với nhiếp ảnh gia"], description: ["Trang điểm chuyên nghiệp cho quảng cáo và sản phẩm", "Phối hợp với ekip nhiếp ảnh, đạo diễn theo yêu cầu", "Makeup HD bền màu dưới mọi điều kiện ánh sáng", "Có thể phục vụ nhiều người trong cùng buổi", "Điều chỉnh linh hoạt theo yêu cầu thương hiệu", "Cung cấp hóa đơn, hợp đồng khi cần"], },
      { id: "bridal",    concept: "Trang điểm cô dâu",  price: 1400000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "travel",    concept: "Trang điểm du lịch",  price: 430000,  duration: "1 giờ",  includes: ["Makeup bền màu", "Chịu nắng và nước tốt"], description: ["Makeup bền màu, chịu nắng và nước tốt", "Phong cách tươi sáng, tự nhiên phù hợp ảnh du lịch", "Sử dụng sản phẩm chống nắng tích hợp trong makeup", "Di chuyển đến địa điểm theo yêu cầu", "Tư vấn màu sắc phù hợp bối cảnh du lịch", "Hoàn thành trong vòng 1 giờ"], },
      { id: "daily",     concept: "Trang điểm hằng ngày", price: 260000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Mỹ Linh",
        reviewerLocation: "Cẩm Lệ, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "05/05/2025",
        rating: 5,
        comment: "Chị Cường trang điểm cho mình đi dự tiệc, rất đẹp và lâu trôi. Sẽ giới thiệu cho bạn bè.",
        reply: "Cảm ơn Mỹ Linh! Hẹn gặp lại lần sau nhé.",
      },
      {
        id: "r2",
        reviewerName: "Hồng Nhung",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "14/03/2025",
        rating: 5,
        comment: "Makeup cô dâu rất chuyên nghiệp, chị đến đúng giờ và phong cách rất đẹp.",
      },
    ],
  },
  {
    id: "p-huyen-my",
    name: "P.Huyền My",
    district: "Thanh Khê",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup5.jpg",
    avatar: "/images/avatar.png",
    bio: "Nghệ sĩ trang điểm chuyên nghiệp với phong cách tươi sáng, trẻ trung. Tôi đặc biệt yêu thích trang điểm cho các bạn trẻ đi du lịch, chụp ảnh ngoại cảnh để có những khoảnh khắc đẹp nhất.",
    bookingArea: "Thanh Khê, Hải Châu, Cẩm Lệ – Đà Nẵng",
    workPrinciples: [
      "Phong cách trẻ trung, tươi sáng là thế mạnh",
      "Sẵn sàng di chuyển đến địa điểm chụp ảnh",
      "Tư vấn màu son và phấn phù hợp tông da",
      "Không tăng giá đột xuất",
    ],
    stats: { profiles: 70, reviews: 65, services: 4, agreements: 120 },
    portfolio: [
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Du lịch" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Ngoại cảnh" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Hằng ngày" },
    ],
    services: [
      { id: "travel",  concept: "Trang điểm du lịch",  price: 400000,  duration: "1 giờ",  includes: ["Makeup bền màu", "Chịu nắng và nước tốt", "Di chuyển đến địa điểm"], description: ["Makeup bền màu, chịu nắng và nước tốt", "Phong cách tươi sáng, tự nhiên phù hợp ảnh du lịch", "Sử dụng sản phẩm chống nắng tích hợp trong makeup", "Di chuyển đến địa điểm theo yêu cầu", "Tư vấn màu sắc phù hợp bối cảnh du lịch", "Hoàn thành trong vòng 1 giờ"], },
      { id: "outdoor", concept: "Trang điểm ngoại cảnh", price: 500000, duration: "1–2 giờ", includes: ["Makeup phù hợp chụp ngoài trời", "Tư vấn màu sắc theo background"], description: ["Makeup tối ưu cho ánh sáng tự nhiên ngoài trời", "Tư vấn màu sắc phù hợp với background và trang phục", "Sản phẩm chống nắng, chịu nhiệt độ cao", "Di chuyển đến địa điểm chụp theo yêu cầu", "Phối hợp với nhiếp ảnh gia để đạt kết quả tốt nhất", "Hoàn thành trong vòng 1–2 giờ"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 250000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, tự nhiên", "Tươi sáng, trẻ trung"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 520000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Quỳnh Như",
        reviewerLocation: "Thanh Khê, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "18/05/2025",
        rating: 5,
        comment: "Đặt lịch đi chụp ảnh du lịch, chị My makeup rất đẹp và phù hợp bối cảnh ngoài trời.",
        reply: "Cảm ơn bạn đã chọn mình! Bộ ảnh của bạn chắc sẽ rất xinh.",
      },
      {
        id: "r2",
        reviewerName: "Diệu Linh",
        reviewerLocation: "Cẩm Lệ, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "01/04/2025",
        rating: 5,
        comment: "Makeup nhẹ nhàng tự nhiên rất hợp với mình. Chị tư vấn rất nhiệt tình.",
      },
    ],
  },
  {
    id: "khanh-van",
    name: "Khánh Vân",
    district: "Hải Châu",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup1.jpg",
    avatar: "/images/avatar.png",
    bio: "Với bề dày kinh nghiệm trang điểm sân khấu và truyền hình, tôi hiểu rõ cách ánh đèn và góc máy ảnh hưởng đến makeup. Đây là lợi thế giúp tôi mang lại kết quả hoàn hảo cho mọi loại sự kiện.",
    bookingArea: "Hải Châu, Thanh Khê, Sơn Trà – Đà Nẵng",
    workPrinciples: [
      "Kinh nghiệm makeup sân khấu và truyền hình",
      "Làm việc được dưới áp lực thời gian cao",
      "Phục vụ nhiều người trong cùng một buổi",
      "Sử dụng airbrush foundation cho độ phủ hoàn hảo",
    ],
    stats: { profiles: 110, reviews: 95, services: 7, agreements: 190 },
    portfolio: [
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Sân khấu" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Truyền hình" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Sự kiện" },
    ],
    services: [
      { id: "stage",   concept: "Trang điểm sân khấu", price: 1000000, duration: "2–3 giờ", includes: ["Makeup sân khấu chuyên nghiệp", "Airbush foundation", "Touch-up không giới hạn"], description: ["Trang điểm sân khấu chuyên nghiệp, bắt đèn tốt", "Sử dụng airbrush foundation cho độ phủ hoàn hảo", "Makeup bền lâu dưới ánh đèn sân khấu cường độ cao", "Có thể phục vụ nhiều nghệ sĩ trong cùng buổi diễn", "Đúng giờ, làm việc được dưới áp lực thời gian", "Touch-up không giới hạn trong suốt sự kiện"], },
      { id: "tv",      concept: "Trang điểm truyền hình", price: 1200000, duration: "2–3 giờ", includes: ["Makeup HD truyền hình", "Phối hợp với đạo diễn", "Xử lý ánh đèn studio"], description: ["Makeup HD chuyên biệt cho quay phim và truyền hình", "Hiểu rõ cách ánh đèn studio ảnh hưởng đến makeup", "Phối hợp với đạo diễn và quay phim theo yêu cầu", "Kinh soát bóng dầu và phản sáng camera hiệu quả", "Điều chỉnh nhanh giữa các cảnh quay", "Cung cấp hóa đơn, hợp đồng khi cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 650000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Airbrush foundation", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1500000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "photo",   concept: "Trang điểm chụp ảnh", price: 750000,  duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Phối hợp với nhiếp ảnh gia"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Lan Hương",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "25/05/2025",
        rating: 5,
        comment: "Chị Vân makeup cho cả đội nhóm sự kiện của mình, rất nhanh và đều đẹp. Rất chuyên nghiệp.",
        reply: "Cảm ơn đội nhóm đã tin tưởng! Rất vui được hợp tác.",
      },
      {
        id: "r2",
        reviewerName: "Tú Uyên",
        reviewerLocation: "Thanh Khê, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "11/04/2025",
        rating: 5,
        comment: "Makeup cho buổi ra mắt sản phẩm, chị làm rất chuyên nghiệp, đúng style thương hiệu yêu cầu.",
      },
    ],
  },
  {
    id: "nguyet-minh",
    name: "Nguyệt Minh",
    district: "Ngũ Hành Sơn",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup2.jpg",
    avatar: "/images/avatar.png",
    bio: "Tôi là makeup artist tự do với phong cách sáng tạo, luôn cập nhật xu hướng mới nhất. Tôi tin rằng mỗi bộ trang điểm là một tác phẩm nghệ thuật được cá nhân hoá cho từng người.",
    bookingArea: "Ngũ Hành Sơn, Cẩm Lệ – Đà Nẵng",
    workPrinciples: [
      "Luôn cập nhật xu hướng makeup mới nhất",
      "Mang theo đầy đủ dụng cụ và phụ kiện dự phòng",
      "Tôn trọng mong muốn và không áp đặt phong cách",
      "Chụp ảnh lưu lại kết quả để tham khảo lần sau",
    ],
    stats: { profiles: 65, reviews: 58, services: 4, agreements: 105 },
    portfolio: [
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Sáng tạo" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Chụp ảnh" },
    ],
    services: [
      { id: "creative", concept: "Trang điểm sáng tạo", price: 800000, duration: "2–3 giờ", includes: ["Concept makeup độc đáo", "Tư vấn ý tưởng cùng khách", "Chụp ảnh lưu kết quả"], description: ["Concept makeup độc đáo, cá nhân hóa cho từng khách", "Tư vấn ý tưởng và tham khảo inspirations cùng khách hàng", "Sử dụng màu sắc và kỹ thuật đa dạng, sáng tạo", "Chụp ảnh lưu kết quả để tham khảo lần sau", "Phù hợp cho chụp ảnh nghệ thuật, cosplay, concept shoot", "Trang điểm tại studio hoặc địa điểm theo yêu cầu"], },
      { id: "bridal",   concept: "Trang điểm cô dâu",  price: 1300000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "photo",    concept: "Trang điểm chụp ảnh", price: 680000, duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Tư vấn concept ảnh"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "event",    concept: "Trang điểm sự kiện",  price: 540000, duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Khánh Linh",
        reviewerLocation: "Ngũ Hành Sơn, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "07/05/2025",
        rating: 5,
        comment: "Makeup rất sáng tạo và độc đáo. Chị Minh hiểu ý mình ngay từ đầu buổi tư vấn.",
        reply: "Cảm ơn bạn! Mình rất vui vì bạn thích concept lần này.",
      },
      {
        id: "r2",
        reviewerName: "Bích Ngân",
        reviewerLocation: "Cẩm Lệ, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "19/03/2025",
        rating: 5,
        comment: "Chị làm makeup cho buổi kỷ niệm 1 năm của mình và bạn trai, rất lãng mạn và đẹp.",
      },
    ],
  },
  {
    id: "ha-minh-phuong",
    name: "Hà Minh Phương",
    district: "Thanh Khê",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup5.jpg",
    avatar: "/images/avatar.png",
    bio: "Tốt nghiệp chuyên ngành Thiết kế thẩm mỹ, tôi áp dụng kiến thức nền tảng về màu sắc và hình thể vào từng bộ trang điểm. Tôi đặc biệt chú trọng đến việc chăm sóc da trước và sau khi makeup.",
    bookingArea: "Thanh Khê, Liên Chiểu – Đà Nẵng",
    workPrinciples: [
      "Tư vấn skincare trước makeup",
      "Áp dụng kiến thức màu sắc học chuyên sâu",
      "Luôn vệ sinh và khử trùng dụng cụ",
      "Có chứng chỉ đào tạo chuyên nghiệp",
    ],
    stats: { profiles: 72, reviews: 63, services: 5, agreements: 115 },
    portfolio: [
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Chăm sóc da" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Sự kiện" },
    ],
    services: [
      { id: "bridal",   concept: "Trang điểm cô dâu",  price: 1400000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Skincare prep", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",    concept: "Trang điểm sự kiện",  price: 560000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Skincare prep", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "skincare", concept: "Chăm sóc da + Makeup", price: 700000, duration: "2 giờ",   includes: ["Skincare chuyên sâu", "Makeup tự nhiên", "Tư vấn routine da"], description: ["Kết hợp chăm sóc da chuyên sâu trước khi makeup", "Tư vấn routine skincare phù hợp với loại da", "Sử dụng sản phẩm skincare chính hãng, an toàn", "Makeup tự nhiên, tôn lên vẻ đẹp của làn da khỏe", "Tư vấn cách chăm sóc da sau khi tẩy trang", "Thời gian bao gồm cả skincare prep và makeup"], },
      { id: "photo",    concept: "Trang điểm chụp ảnh", price: 680000, duration: "1–2 giờ", includes: ["Makeup chụp ảnh", "Skincare prep", "Tư vấn concept"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "daily",    concept: "Trang điểm hằng ngày", price: 280000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, bài bản", "Tư vấn màu sắc học"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Ngọc Hân",
        reviewerLocation: "Thanh Khê, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "28/04/2025",
        rating: 5,
        comment: "Chị Phương tư vấn rất kỹ về cách chăm sóc da trước ngày cưới. Makeup đẹp và da mình đỡ hẳn.",
        reply: "Cảm ơn bạn! Chúc đám cưới vui vẻ và hạnh phúc nhé.",
      },
      {
        id: "r2",
        reviewerName: "Bảo Trân",
        reviewerLocation: "Liên Chiểu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "06/03/2025",
        rating: 5,
        comment: "Makeup rất sạch, chuẩn kỹ thuật. Nhìn vào biết ngay chị được đào tạo bài bản.",
      },
    ],
  },
  {
    id: "trang-leo",
    name: "Trang Leo",
    district: "Cẩm Lệ",
    city: "Đà Nẵng",
    rating: 5.0,
    coverPhoto: "/images/makeup1.jpg",
    avatar: "/images/avatar.png",
    bio: "Mình là Trang Leo – makeup artist trẻ nhưng đầy nhiệt huyết. Mình đặc biệt yêu thích phong cách glam và bold makeup cho các bữa tiệc, sự kiện đêm. Mỗi khách hàng là một nguồn cảm hứng mới.",
    bookingArea: "Cẩm Lệ, Hải Châu – Đà Nẵng",
    workPrinciples: [
      "Chuyên phong cách glam và bold",
      "Lắng nghe ý tưởng và biến nó thành hiện thực",
      "Luôn mang theo bộ sản phẩm dự phòng",
      "Chia sẻ tips makeup sau buổi làm",
    ],
    stats: { profiles: 55, reviews: 50, services: 3, agreements: 90 },
    portfolio: [
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Glam" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Tiệc đêm" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Bold" },
    ],
    services: [
      { id: "glam",   concept: "Trang điểm Glam",    price: 700000,  duration: "1–2 giờ", includes: ["Makeup glam sang chảnh", "Phù hợp dự tiệc, lễ hội"], description: ["Phong cách glam sang chảnh, phù hợp dự tiệc và lễ hội", "Contouring, highlight chuyên nghiệp theo khuôn mặt", "Dùng sản phẩm cao cấp bền màu cả đêm", "Tư vấn phong cách phù hợp với trang phục", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu"], },
      { id: "party",  concept: "Trang điểm tiệc đêm", price: 650000,  duration: "1–2 giờ", includes: ["Makeup tiệc đêm bắt đèn", "Smokey eye, highlight"], description: ["Makeup tiệc đêm bắt đèn, smokey eye và highlight rực rỡ", "Sản phẩm bền lâu, chống trôi suốt đêm tiệc", "Tư vấn màu mắt và son phù hợp với outfit", "Phong cách táo bạo hoặc quyến rũ theo yêu cầu", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "bold",   concept: "Trang điểm Bold",    price: 750000,  duration: "1–2 giờ", includes: ["Makeup nghệ thuật, cá tính", "Chụp ảnh, concept sáng tạo"], description: ["Makeup nghệ thuật, cá tính và đầy sáng tạo", "Phù hợp cho chụp ảnh concept, editorial, fashion", "Sử dụng màu sắc độc đáo, kỹ thuật đa dạng", "Tư vấn ý tưởng và tham khảo inspirations", "Chụp ảnh lưu lại kết quả sau buổi makeup", "Trang điểm tại studio hoặc địa điểm theo yêu cầu"], },
      { id: "event",  concept: "Trang điểm sự kiện",  price: 500000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Như Quỳnh",
        reviewerLocation: "Cẩm Lệ, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "02/05/2025",
        rating: 5,
        comment: "Trang làm makeup tiệc cho mình cực đẹp! Phong cách glam đúng mình thích. Sẽ book lại.",
        reply: "Cảm ơn bạn yêu! Lần sau có tiệc nhớ tìm Trang nhé.",
      },
      {
        id: "r2",
        reviewerName: "Mai Ly",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "15/02/2025",
        rating: 5,
        comment: "Makeup cực kỳ sáng tạo và đẹp. Trang rất thân thiện và làm mình thoải mái suốt buổi.",
      },
    ],
  },
  {
    id: "minh-tu",
    name: "Minh Tú",
    district: "Liên Chiểu",
    city: "Đà Nẵng",
    rating: 4.9,
    coverPhoto: "/images/makeup2.jpg",
    avatar: "/images/avatar.png",
    bio: "Chuyên gia trang điểm với phong cách hiện đại, tôi luôn cố gắng mang lại sự tự tin cho khách hàng thông qua từng nét cọ. Tôi có nhiều kinh nghiệm làm việc với các nhiếp ảnh gia chuyên nghiệp.",
    bookingArea: "Liên Chiểu, Hải Châu – Đà Nẵng",
    workPrinciples: [
      "Phối hợp tốt với nhiếp ảnh gia và ekip",
      "Makeup tốt dưới mọi điều kiện ánh sáng",
      "Linh hoạt điều chỉnh theo yêu cầu của nhiếp ảnh gia",
      "Cam kết thời gian và chất lượng",
    ],
    stats: { profiles: 90, reviews: 80, services: 5, agreements: 160 },
    portfolio: [
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Chụp ảnh" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Cô dâu" },
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Sự kiện" },
    ],
    services: [
      { id: "photo",   concept: "Trang điểm chụp ảnh", price: 720000, duration: "1–2 giờ", includes: ["Makeup chụp ảnh studio/ngoại cảnh", "Phối hợp với nhiếp ảnh gia", "Điều chỉnh theo ánh sáng"], description: ["Trang điểm tối ưu cho camera, ánh sáng studio và ngoại cảnh", "Phối hợp chặt chẽ với nhiếp ảnh gia", "Sử dụng sản phẩm kiểm soát bóng dầu bền lâu", "Tư vấn concept và màu sắc phù hợp với bối cảnh chụp", "Điều chỉnh linh hoạt giữa các set ảnh", "Trang điểm tại studio hoặc địa điểm chụp theo yêu cầu"], },
      { id: "bridal",  concept: "Trang điểm cô dâu",  price: 1350000, duration: "3–4 giờ", includes: ["Makeup cô dâu + phù dâu", "Touch-up 2 lần", "Tư vấn trước ngày cưới"], description: ["Trang điểm cô dâu nhẹ nhàng, bền màu suốt cả ngày", "Dịch vụ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho mọi loại da", "Chăm sóc da và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hỗ trợ touch-up trong suốt sự kiện nếu cần"], },
      { id: "event",   concept: "Trang điểm sự kiện",  price: 560000,  duration: "1–2 giờ", includes: ["Makeup sự kiện", "Lựa chọn phong cách", "Touch-up 1 lần"], description: ["Phong cách trang điểm phù hợp với từng loại sự kiện", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín, an toàn cho da", "Tư vấn phong cách trước buổi hẹn", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 270000, duration: "45 phút", includes: ["Makeup nhẹ nhàng, hiện đại"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Phương Thảo",
        reviewerLocation: "Liên Chiểu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "30/04/2025",
        rating: 5,
        comment: "Chị Tú phối hợp rất tốt với nhiếp ảnh gia, makeup đẹp cả trong ảnh lẫn ngoài thực tế.",
        reply: "Cảm ơn bạn! Rất vui được làm việc cùng ekip chuyên nghiệp.",
      },
      {
        id: "r2",
        reviewerName: "Hải Yến",
        reviewerLocation: "Hải Châu, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "12/03/2025",
        rating: 4,
        comment: "Chị làm rất tốt, chỉ hơi trễ một chút nhưng kết quả thì xứng đáng.",
      },
    ],
  },
  {
    id: "bao-chau",
    name: "Bảo Châu",
    district: "Sơn Trà",
    city: "Đà Nẵng",
    rating: 4.8,
    coverPhoto: "/images/makeup5.jpg",
    avatar: "/images/avatar.png",
    bio: "Tôi là Bảo Châu, makeup artist tại Sơn Trà với sở trường trang điểm tự nhiên và trong sáng. Tôi tin rằng vẻ đẹp thực sự đến từ bên trong và công việc của tôi chỉ là giúp tô điểm thêm cho vẻ đẹp đó.",
    bookingArea: "Sơn Trà, Ngũ Hành Sơn – Đà Nẵng",
    workPrinciples: [
      "Tôn vinh vẻ đẹp tự nhiên của khách hàng",
      "Không trang điểm quá đà so với yêu cầu",
      "Tư vấn chân thành về điểm mạnh của từng người",
      "Giá cả hợp lý, phù hợp mọi đối tượng",
    ],
    stats: { profiles: 60, reviews: 52, services: 3, agreements: 95 },
    portfolio: [
      { images: ["/images/makeup5.jpg", "/images/makeup1.jpg", "/images/makeup2.jpg"], label: "Tự nhiên" },
      { images: ["/images/makeup1.jpg", "/images/makeup2.jpg", "/images/makeup5.jpg"], label: "Hằng ngày" },
      { images: ["/images/makeup2.jpg", "/images/makeup5.jpg", "/images/makeup1.jpg"], label: "Du lịch" },
    ],
    services: [
      { id: "natural", concept: "Trang điểm tự nhiên",  price: 280000, duration: "45 phút", includes: ["Makeup tự nhiên, trong sáng", "Tôn lên vẻ đẹp tự có"], description: ["Tôn vinh vẻ đẹp tự nhiên, không trang điểm quá đà", "Phong cách trong sáng, tươi tắn và tự tin", "Sử dụng sản phẩm nhẹ nhàng, an toàn cho da nhạy cảm", "Tư vấn chân thành về điểm mạnh của từng khuôn mặt", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu"], },
      { id: "daily",   concept: "Trang điểm hằng ngày", price: 250000, duration: "45 phút", includes: ["Makeup nhẹ nhàng", "Phù hợp đi làm, đi học"], description: ["Phong cách trang điểm nhẹ, phù hợp với trang phục hằng ngày", "Dịch vụ chỉ bao gồm trang điểm, không bao gồm làm tóc", "Sử dụng mỹ phẩm uy tín và an toàn cho da, phù hợp mọi loại da", "Chăm sóc da nhanh và che khuyết điểm trước khi trang điểm", "Đúng giờ, nhiệt tình và có trách nhiệm", "Trang điểm tại nhà hoặc địa điểm theo yêu cầu", "Hoàn thành trong vòng 1 giờ 30 phút"], },
      { id: "travel",  concept: "Trang điểm du lịch",  price: 380000,  duration: "1 giờ",  includes: ["Makeup bền màu", "Tự nhiên phù hợp ảnh du lịch"], description: ["Makeup bền màu, chịu nắng và nước tốt", "Phong cách tươi sáng, tự nhiên phù hợp ảnh du lịch", "Sử dụng sản phẩm chống nắng tích hợp trong makeup", "Di chuyển đến địa điểm theo yêu cầu", "Tư vấn màu sắc phù hợp bối cảnh du lịch", "Hoàn thành trong vòng 1 giờ"], },
    ],

    reviews: [
      {
        id: "r1",
        reviewerName: "Trà My",
        reviewerLocation: "Sơn Trà, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "22/04/2025",
        rating: 5,
        comment: "Mình thích phong cách tự nhiên và chị Châu làm đúng ý mình. Makeup nhẹ mà vẫn rạng rỡ.",
        reply: "Cảm ơn bạn đã yêu mến! Hẹn gặp lại lần sau nhé.",
      },
      {
        id: "r2",
        reviewerName: "Hoài Thương",
        reviewerLocation: "Ngũ Hành Sơn, Đà Nẵng",
        reviewerAvatar: "/images/avatar.png",
        date: "08/02/2025",
        rating: 4,
        comment: "Chị làm khá ổn, phong cách tự nhiên đúng mô tả. Mình hài lòng với dịch vụ.",
      },
    ],
  },
];

export function getArtistById(id: string): ArtistProfile | undefined {
  return ARTIST_PROFILES.find((a) => a.id === id);
}
